"""Generate the GPU sweep files (docs/GPU_GO_NO_GO.md) from one spec, so the grid lives in code.

Stages:
  g1  calibration: pure attention / pure Mamba-2 / pure Gated DeltaNet x L in {64, 256, 512} x per-family LR grid,
      1 seed. Answers trainability at depth 8, informative (L, K) region, LR ranges.
  g2  broad ratio map: r in {0, 1/8, 1/4, 1/2, 1} x 2 families x L grid x per-family LR grid, 1 seed.
  g3  replication: seeds 1 and 2 at the validation-selected LR (written after g2 by --stage g3 --lr-table).

Each sweep file trains on a round-robin mixture of memory loads K for one sequence length L and evaluates
every K separately, so one run yields a full accuracy-vs-K curve at that L.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import yaml

OUT = Path("configs/sweeps/gpu")

# Memory loads per length: keys + values occupy 2K positions and K queries need free slots, so 4K <= L.
LOADS = {64: [4, 8, 16], 128: [8, 16, 32], 256: [16, 32, 64], 512: [32, 64, 128]}
LR_GRID = {  # per family; centred on the CPU pilot optima (log entry 06), widened one step each side
    "attention": [3e-4, 1e-3, 3e-3, 1e-2],
    "mamba2": [1e-3, 3e-3, 1e-2, 3e-2],
    "gdn": [3e-4, 1e-3, 3e-3, 1e-2],
}
MODEL = {
    "vocab_size": 528,  # 1 + 256 keys + 256 values, padded
    "d_model": 128,
    "n_layers": 8,
    "placement": "block_end",
    "attn_heads": 4,  # head dim 32
    "gdn_heads": 4,
    "mamba_head_dim": 16,
    "mamba_d_state": 16,
    "chunk": 64,
}
TRAINING = {
    "steps": 20000,
    "batch_size": 64,
    "eval_every": 1000,
    "n_eval": 1000,
    "n_val": 500,
    "warmup_frac": 0.02,
}


def spec_for(L: int) -> list[dict]:
    return [{"seq_len": L, "difficulty": {"num_pairs": k, "key_vocab": 256, "value_vocab": 256}} for k in LOADS[L]]


def sweep(name: str, family: str, n_attn: list[int], L: int, lrs: list[float], seeds: list[int]) -> dict:
    fam = "mamba2" if family == "attention" else family
    return {
        "name": name,
        "base": {
            "task": "mqar",
            "model": {**MODEL, "family": fam, "n_attn": n_attn[0]},
            "train": spec_for(L),
            "eval": spec_for(L),
            **TRAINING,
            "lr": lrs[0],
        },
        "grid": {"model.n_attn": n_attn, "lr": lrs, "seed": seeds},
    }


def write(stage: str, sweeps: list[tuple[str, dict]]) -> None:
    d = OUT / stage
    d.mkdir(parents=True, exist_ok=True)
    for fname, sw in sweeps:
        header = f"# Generated by scripts/make_gpu_sweeps.py --stage {stage}. Do not edit by hand.\n"
        (d / fname).write_text(header + yaml.safe_dump(sw, sort_keys=False))
    print(f"wrote {len(sweeps)} sweep files to {d}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--stage", choices=["g1", "g2", "g3"], required=True)
    ap.add_argument("--lr-table", help="g3: JSON {family/n_attn/L: lr} from the g2 validation selection")
    args = ap.parse_args()
    if args.stage == "g1":
        out = []
        for L in (64, 256, 512):
            out.append((f"attention_L{L}.yaml", sweep("gpu_g1", "attention", [8], L, LR_GRID["attention"], [0])))
            for fam in ("mamba2", "gdn"):
                out.append((f"{fam}_L{L}.yaml", sweep("gpu_g1", fam, [0], L, LR_GRID[fam], [0])))
        write("g1", out)
    elif args.stage == "g2":
        out = []
        for L in sorted(LOADS):
            out.append((f"attention_L{L}.yaml", sweep("gpu_g2", "attention", [8], L, LR_GRID["attention"], [0])))
            for fam in ("mamba2", "gdn"):
                out.append((f"{fam}_L{L}.yaml", sweep("gpu_g2", fam, [0, 1, 2, 4], L, LR_GRID[fam], [0])))
        write("g2", out)
    else:
        if not args.lr_table:
            raise SystemExit("--stage g3 needs --lr-table from the g2 analysis")
        table = json.loads(Path(args.lr_table).read_text())
        out = []
        for key, lr in table.items():
            fam, n_attn, L = key.split("/")
            out.append((f"{fam}_a{n_attn}_L{L}.yaml", sweep("gpu_g3", fam, [int(n_attn)], int(L), [float(lr)], [1, 2])))
        write("g3", out)


if __name__ == "__main__":
    main()
